export default {
	UNKNOWN_ERROR: 'UNKNOWN_ERROR',
	GET_COMPANY_INFO_ERROR: 'GET_COMPANY_INFO_ERROR',
	GET_CATEGORY_TITLES: 'GET_CATEGORY_TITLES',
	GET_POSTS_ERROR: 'GET_COMPANY_INFO_ERROR',
	GET_COMMENTS_ERROR: 'GET_COMMENTS_ERROR',
	SUBSCRIBE_ERROR: 'SUBSCRIBE_ERROR',
	LIKE_ERROR: 'LIKE_ERROR',
	COMMENT_ERROR: 'COMMENT_ERROR',
	UNABLE_TO_AUTHORIZE: 'UNABLE_TO_AUTHORIZE'
};
